/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author zhengyu
 */
public enum CourseSitePropertyType {
    // TABS
    CSG_SITE, 
    CSG_SYLLABUS,
    CSG_MEETING,
    CSG_OH,
    CSG_SCHEDULE,
    CSG_GRID_PANE,
    CSG_SCROLL_PANE,
    CSG_FOOLPROOF_SETTINGS,
    // SITE TAB 
    SITE_BANNER_BOX,
    SITE_PAGE_BOX,
    SITE_STYLE_BOX,
    SITE_INSTRUCTOR_BOX,
    SITE_BANNER,
    SITE_SUBJECT,
    SITE_SUBJECT_COMBO_BOX,
    SITE_YEAR,
    SITE_YEAR_COMBO_BOX,
    SITE_SEMESTER,
    SITE_SEMESTER_COMBO_BOX,
    SITE_NUMBER,
    SITE_NUMBER_COMBO_BOX,
    SITE_TITLE,
    SITE_TITLE_TEXT_FIELD,
    SITE_EXPORT,
    SITE_PAGE,
    SITE_HOME,
    SITE_SYLLABUS,
    SITE_SCHEDULE,
    SITE_HWS,
    SITE_STYLE,
    SITE_FAVICON,
    SITE_NAVBAR,
    SITE_LEFT_FOOTER,
    SITE_RIGHT_FOOTER,
    SITE_FAVICON_IMG,
    SITE_NAVBAR_IMG,
    SITE_LEFT_FOOTER_IMG,
    SITE_RIGHT_FOOTER_IMG,
    SITE_CSS,
    SITE_CSS_COMBO_BOX,
    SITE_NOTE,
    SITE_INSTRUCTOR,
    SITE_INSTRUCTOR_NAME,
    SITE_INSTRUCTOR_NAME_TEXT_FIELD,
    SITE_INSTRUCTOR_ROOM,
    SITE_INSTRUCTOR_ROOM_TEXT_FIELD,
    SITE_INSTRUCTOR_EMAIL,
    SITE_INSTRUCTOR_EMAIL_TEXT_FIELD,
    SITE_INSTRUCTOR_HOMEPAGE,
    SITE_INSTRUCTOR_HOMEPAGE_TEXT_FIELD,
    SITE_INSTRUCTOR_OH,
    SITE_INSTRUCTOR_OH_TEXT_AREA,
    
    
    //OH VARIABLES
    OH_BOX,
    OH_TA_BOX,
    OH_OFFICE_HOURS_BOX,
    OH_TAS_TOGGLE,
    OH_TAS_HEADER_LABEL,
    OH_TAS_HEADER_TEXT_FIELD,
    OH_TAS_TABLE_VIEW,
    OH_NAME_TABLE_COLUMN,
    OH_EMAIL_TABLE_COLUMN,
    OH_SLOTS_TABLE_COLUMN,
    OH_TYPE_TABLE_COLUMN,
    
    OH_OFFICE_HOURS_HEADER_BOX,
    OH_OFFICE_HOURS_HEADER_LABEL,
    OH_OFFICE_HOURS_TABLE_VIEW,
    OH_START_TIME_TABLE_COLUMN,
    OH_END_TIME_TABLE_COLUMN,
    OH_MONDAY_TABLE_COLUMN,
    OH_TUESDAY_TABLE_COLUMN,
    OH_WEDNESDAY_TABLE_COLUMN,
    OH_THURSDAY_TABLE_COLUMN,
    OH_FRIDAY_TABLE_COLUMN,
    OH_DAYS_OF_WEEK,
    OH_FOOLPROOF_SETTINGS,
    OH_START_TIME_LABLE,
    OH_END_TIME_LABLE,
    OH_START_TIME_COMBO_BOX,
    OH_END_TIME_COMBO_BOX,
    
    OH_MISSING_TA_NAME_TITLE_LABEL,
    OH_MISSING_TA_NAME_MESSAGE,
    
    OH_NAME_TEXT_FIELD,
    OH_EMAIL_TEXT_FIELD,
    OH_ADD_TA_BUTTON,
    OH_REMOVE_TA_BUTTON,
    OH_TOGGLE_ALL,
    OH_TOGGLE_UNDERGRADUATE,
    OH_TOGGLE_GRADUATE,
    OH_EDIT_TA_TITLE,OH_EDIT_TA_TEXT,
    OH_EDIT_TA_TYPE,OH_NAME_TABLE_COLUMN_TEXT,OH_EMAIL_TABLE_COLUMN_TEXT,
    OH_EMAIL_ERROR_TEXT,OH_NAME_ERROR_TEXT,
    
    OH_TOGGLE_UNDERGRADUATE_TEXT,
    OH_TOGGLE_GRADUATE_TEXT,
    //css    
    
}
